### PR TITLE
Enable FinalOrAbstractClassLinter

### PR DESCRIPTION
**Pull request by lexidor**
closes #281

This PR activates the FinalOrAbstractClassLinter.

### CODE REVIEW

**Comment by jjergus** [comment]
I have mixed feelings about this linter... It's a good rule to follow in general, but there are definitely some legitimate exceptions, do we really want to force people to use HHAST_IGNORE_ERROR for those?

It would be nicer if the linter could check for subclasses and instances, but we probably don't have an efficient way to do that right now.

**Comment by lexidor** [comment]
I believe that #13 applies here
We cannot specify what we mean with what linters we enable
You have `all`, which should mean every linter, `default` which means nothing and just comes down to the preference of the linter writer, and `none`
If we are open for it, I think we might want to rethink this

I'll make an issue where others can tell what properties they want to a selection like this

**Comment by jjergus** [comment]
Fair enough, I guess it makes sense for "all" to really mean "all".

This particular one might be a difficult change though, since it's likely to cause lots of lint errors that are not autofixable. Do we know if any big Hack projects use "all"? If almost everyone uses "default" anyway it's probably fine.

**Comment by fredemmott** [comment]
Yeah, this should be in 'all'

However, does the current system allow blacklisting a directory, but not subdirs?

I'd like this blacklisted for src/*.hack, but not e.g. src/Linters/*.hack, src/migrations/*.hack, src/_Private

**Comment by jjergus** [comment]
I think for HHAST enabling this rule is perfectly fine (only requires 2 FIXMEs, less than the Asio\join linter), I'm only worried about other, larger projects that might be using "all". Although I guess they can always add the linter to disabledLinters when updating HHAST to avoid having to address too many lint errors.

**Comment by fredemmott** [comment]
Assuming there's no conflicts, `all` really needs to be all to make sense (and to match the documented behavior; default I see some nuance, but projects that opt in to all should expect to get new linters they may disagree with or may be impractical.

Any non-conflicting linters that aren't in all are an oversight

**Comment by lexidor** [comment]
I have pulled in as many dependencies as were compatible with eachother and ran FinalOrAbstractClassLinter over vendor.

```
  - Installing hhvm/hsl (dev-master 86966f5): Cloning 86966f541a from cache
  - Installing hhvm/hhvm-autoload (dev-master ce6045f): Cloning ce6045f61a from cache
  - Installing hhvm/type-assert (dev-master 4a38eaf): Cloning 4a38eaf4fe from cache
  - Installing nuxed/json (v1.0.2): Loading from cache
  - Installing hhvm/hsl-experimental (dev-master d06cdd4): Cloning d06cdd41fc from cache
  - Installing nuxed/filesystem (v1.2.3): Loading from cache
  - Installing nuxed/contract (v0.2.0): Loading from cache
  - Installing nuxed/translation (v1.0.0): Loading from cache
  - Installing facebook/hh-clilib (dev-master 19dda71): Cloning 19dda71376 from cache
  - Installing hhvm/hacktest (dev-master 7d7da8d): Cloning 7d7da8df11 from cache
  - Installing facebook/difflib (dev-master b151d1a): Cloning b151d1a2f8 from cache
  - Installing hhvm/hhast (dev-master 078f893): Cloning 078f893f55 from cache
  - Installing facebook/definition-finder (dev-master dcca6c2): Cloning dcca6c27cd from cache
  - Installing facebook/fbmarkdown (dev-master 85dedfd): Cloning 85dedfd2c1 from cache
  - Installing facebook/hack-http-request-response-interfaces (v0.3): Loading from cache
  - Installing facebook/hack-router (v0.19.6): Loading from cache
  - Installing facebook/hack-codegen (v4.3.9): Loading from cache
  - Installing facebook/hack-router-codegen (dev-master 613ffaf): Cloning 613ffafe2a from cache
  - Installing facebook/xhp-lib (dev-master 954fb12): Cloning 954fb12714 from cache
  - Installing nuxed/asset (dev-master 7e5653d): Cloning 7e5653d350 from cache
  - Installing nuxed/environment (dev-master cb27fe2): Cloning cb27fe268c from cache
  - Installing nuxed/http-emitter (dev-master 98763e6): Cloning 98763e613a from cache
  - Installing azjezz/http-normalizer (v1.0.1): Loading from cache
  - Installing nuxed/http-message (dev-master f46c017): Cloning f46c017de7 from cache
  - Installing nuxed/inflector (dev-master e0d717b): Cloning e0d717b679 from cache
  - Installing nuxed/crypto (v1.0.4): Loading from cache
  - Installing nuxed/uuid (dev-master eee1498): Cloning eee1498516 from cache
  - Installing usox/hack-http-factory-interfaces (v0.2.2): Loading from cache
  - Installing usox/hackttp (dev-master 745189a): Cloning 745189ad8d from cache
  - Installing facebook/fbexpect (v2.7.3): Loading from cache
  - Installing usox/hackmock (dev-master d667923): Cloning d667923c86 from cache
  - Installing usox/sharesta (dev-master 654f6a0): Cloning 654f6a0705 from cache
```

There are 413 lint errors (this includes the ones already fixed in this PR)

 - [hhvm/xhp-lib](https://github.com/hhvm/xhp-lib) (187)
 - [hhvm/definition-finder](https://github.com/hhvm/definition-finder) (57)
 - [hhvm/fbmarkdown](https://github.com/hhvm/fbmarkdown) (53)
 - [usox/hackttp](https://github.com/usox/hackttp) (14)
 - [usox/sharesta](https://github.com/usox/sharesta) (10)
 - [nuxed/http-message](https://github.com/nuxed/http-message) (10)
 - [nuxed/asset](https://github.com/nuxed/asset) (10)
 - [hhvm/hhvm-autoload](https://github.com/hhvm/hhvm-autoload) (8)
 - [usox/hackmock](https://github.com/usox/hackmock) (6)
 - [hhvm/hack-router](https://github.com/hhvm/hack-router) (6)
 - [nuxed/translation](https://github.com/nuxed/translation) (5)
 - [nuxed/contract](https://github.com/nuxed/contract) (4)
 - [nuxed/contract](https://github.com/nuxed/contract) (4)
 - [hhvm/hh-clilib](https://github.com/hhvm/hh-clilib) (3)
 - [hhvm/type-assert](https://github.com/hhvm/type-assert) (3)
 - [hhvm/hack-codegen](https://github.com/hhvm/hack-codegen) (2)
 - [nuxed/crypto](https://github.com/nuxed/crypto) (2)
 - [nuxed/filesystem](https://github.com/nuxed/filesystem) (2)
 - [hhvm/hack-router-codegen](https://github.com/hhvm/hack-router-codegen) (1)
 - [nuxed/inflector](https://github.com/nuxed/inflector) (1)
 - [nuxed/environment](https://github.com/nuxed/environment) (1)
 - [nuxed/uuid](https://github.com/nuxed/uuid) (1)
 - [hhvm/hsl-experimental](https://github.com/hhvm/hsl-experimental) (1)
 - [hhvm/hacktest](https://github.com/hhvm/hacktest) (1)
 - [hhvm/hsl](https://github.com/hhvm/hsl) (1)

https://hastebin.com/habafaboxo.http

**Comment by lexidor** [comment]
This does not ignore `codegen/` and friends, so the actual number of errors that people are going to see is lower.

**Comment by fredemmott** [comment]
> hhvm/xhp-lib (187)


These should be changed - I wouldn't expect extending any of the HTML classes to end well :/ XHP really needs composition over inheritance.

**Comment by lexidor** [comment]
This linter has more errors than any other linter:
```
dict(25) {
  ["Facebook\HHAST\UseStatementWithAsLinter"]=>
  int(175)
  ["Facebook\HHAST\PreferSingleQuotedStringLiteralLinter"]=>
  int(158)
  ["Facebook\HHAST\AsyncFunctionAndMethodLinter"]=>
  int(127)
  ["Facebook\HHAST\ShoutCaseEnumMembersLinter"]=>
  int(111)
  ["Facebook\HHAST\UnusedUseClauseLinter"]=>
  int(79)
  ["Facebook\HHAST\MustUseOverrideAttributeLinter"]=>
  int(55)
  ["Facebook\HHAST\CamelCasedMethodsUnderscoredFunctionsLinter"]=>
  int(43)
  ["Facebook\HHAST\NoPHPArrayLiteralsLinter"]=>
  int(28)
  ["Facebook\HHAST\UseStatementWithoutKindLinter"]=>
  int(27)
  ["Facebook\HHAST\UnusedParameterLinter"]=>
  int(20)
  ["Facebook\HHAST\GroupUseStatementsLinter"]=>
  int(19)
  ["Facebook\HHAST\DontUseAsioJoinLinter"]=>
  int(18)
  ["Facebook\HHAST\DontAwaitInALoopLinter"]=>
  int(16)
  ["Facebook\HHAST\StrictModeOnlyLinter"]=>
  int(16)
  ["Facebook\HHAST\UnusedVariableLinter"]=>
  int(15)
  ["Facebook\HHAST\NoWhitespaceAtEndOfLineLinter"]=>
  int(13)
  ["Facebook\HHAST\NoFinalMethodInFinalClassLinter"]=>
  int(13)
  ["Facebook\HHAST\NoStringInterpolationLinter"]=>
  int(12)
  ["Facebook\HHAST\PreferRequireOnceLinter"]=>
  int(10)
  ["Facebook\HHAST\GroupUseStatementAlphabetizationLinter"]=>
  int(9)
  ["Facebook\HHAST\NewlineAtEndOfFileLinter"]=>
  int(6)
  ["Facebook\HHAST\NoPHPEqualityLinter"]=>
  int(5)
  ["Facebook\HHAST\NoBasicAssignmentFunctionParameterLinter"]=>
  int(4)
  ["Facebook\HHAST\NoElseifLinter"]=>
  int(2)
  ["Facebook\HHAST\UseStatementWithLeadingBackslashLinter"]=>
  int(2)
}
```

**Comment by lexidor** [comment]
Must be remade because of conflicting codegen.

**Pull request closed without merging**
