### PR TITLE
Assert to Expect migration

### PR DESCRIPTION
**Pull request by wlin57**
- Migrates assert calls to their respective expect function (let me know if I missed any others that directly translate)
- Adds 'use function Facebook\FBExpect\expect' according to #91 
- Doesn't handle all of the cases with comments correctly...working on it

Will add examples of each case listed in #91 , or perhaps refactor how MigrationsTest works (currently can only test one .in and .expect file)

### CODE REVIEW

**Comment by kmeht** [comment]
Is this meant to migrate tests internally? If so, the `assert*` functions are static methods, not instance methods.

**Comment by fredemmott** [comment]
Test failure looks like a Travis infra fail, triggered a re-run.

**Comment by fredemmott** [comment]
> Adds 'use function Facebook\FBExpect\expect' according to #91

We also don't want this internally except for open source code like the HSL (we have `expect()` in the root namespace that returns a subclass).

Probably best to just comment out this part when running internally rather than add the complexity to fully support making it optional.

**Comment by fredemmott** [comment]
I thought there was a comment saying this was incomplete - is it ready now?

Also, can you test this by sending a PR against an open source FB project (maybe hhast itself?) that includes the results of this migration please

**Comment by wlin57** [comment]
Almost, it doesn't handle some edge cases with comments. However, I think it will work fine for an open source FB project. I'll try definition-finder since hhast doesn't really have any assert calls in its tests.

**Comment by wlin57** [comment]
The latest commit resolves some bugs (found when testing against definition-finder) and updates tests accordingly. The thing with open source is that there's always (?) a copyright comment or some form of namespace or use statement. Unless there are multiple successive non-docblock comments and no namespace/use statements at all, this migration should work as expected for open source.

**Pull request merged**
