### PR TITLE
Make `"builtinLinters": "all"` mean all linters, but...

### PR DESCRIPTION
**Pull request by lexidor**
, but...

I have intentionally not added DataProviderTypesLinter. This was a well intended linter, but it does some things it shouldn't do. Its idea of isSafeAssignment is misguided.

### CODE REVIEW

**Comment by lexidor** [comment]
Got to figure out why hhvm-nightly takes 6 hours and gets killed by github.

**Comment by Atry** [comment]
Close and reopen this PR to trigger the CI

**Comment by lexidor** [comment]
Merge conflict requires running codegen again to fix the file hash in token-from-data.hack. I will have to do that some other day.

**Comment by lexidor** [comment]
Running CI

**Review by Atry — APPROVED** [review]

**Comment by Atry** [comment]
Looks good to me

**Pull request merged**
