### PR TITLE
Use all strict options since HHVM4.8

### PR DESCRIPTION
**Pull request by lexidor**
Build failure: Difflib (already patched)

### CODE REVIEW

**Comment by fredemmott** [comment]
can you rebase this please? Should hopefully have a clean test run now

**Comment by lexidor** [comment]
@fredemmott I have made a mention of all the dependencies that I recognized from the error log above. These repo's all have untyped lambda's. This should allow for a clean build once more.

**Comment by fredemmott** [comment]
difflib's released; this neds a rebase due to the composer.json and .travis.yml changes

**Comment by lexidor** [comment]
I ended looping forever while rebasing.
```
git checkout update/hhvm-versions
git pull
git fetch upstream
git rebase upstream/master --interactive
--Conflict
git add --conflicting file--
git rebase --continue
`Did you want to use git commit --allow-empty`
git commit --allow-empty
git rebase --continue
```
But, it rebased nothing, afaik.

**Comment by lexidor** [comment]
#199 is less effort, since it is branched of the new master.

**Comment by fredemmott** [comment]
Closing in favor of #199

**Pull request closed without merging**
