### PR TITLE
Allow the devcontainer to use the local ssh keys

### PR DESCRIPTION
**Pull request by Atry**
This commit would allow for `git push` from the devcontainer

### CODE REVIEW

**Comment by fredemmott** [comment]
I think this should be doable with the `mounts` argument instead, which will be ignored by github codespaces etc

**Comment by fredemmott** [comment]
This also sounds like it's meant to 'just work': https://code.visualstudio.com/docs/remote/containers#_using-ssh-keys

**Review by fredemmott — CHANGES_REQUESTED** [review]
yep, this shouldn't be needed.

I let vscode set up the container for hhast, then in terminal in vscode:
 - made sure the terminal was inside the container
 - ran `ssh-add -l`
 - saw my keys

**Comment by Atry** [comment]
I executed `ssh-add` and it just work. It seems that the mounting is unnecessary! Thank you!

**Pull request closed without merging**
