### PR TITLE
add NoWhitespaceAtEndOfLineLinter

### PR DESCRIPTION
**Pull request by bradleyhd**
Here's a trailing whitespace AST linter that hopefully addresses #3. Let me know if it needs more tests!

As an aside (I'm pretty new to anything open source), should I be putting the FB copyright headers in new files? Feels weird to be doing that as an outside entity but I'm guessing that's what ultimately needs to happen.

### CODE REVIEW

**Comment by fredemmott** [comment]
Thanks - I'm waiting for a definitive answer on the headers.

This looks fine, though - and this isn't a bad thing - is there a reason this is AST-based rather than line-based?

**Comment by bradleyhd** [comment]
Not really! I wrote a line-based one but got to the autofixing part and ended up with something that wrote the file back to disk repeatedly for each error, which felt wrong. Not sure why I didn't just coalesce them in `fixLintErrors` - happy to get it up and running and send it in as a PR. 

I've also got a mixed tabs/whitespace indent line-based linter if there's interest in having that upstream.

Last but not least, do you think #2 (CLRF) should be in the same linter or a separate one?

**Comment by fredemmott** [comment]
It should be a separate linter - it doesn't seem implausible that people would want CRLF removal, but might not want this linter - for example, if it turns out that this has weird interactions with some node types and creates a load of problems in some code bases.

**Comment by fredemmott** [comment]
The standard license header is definitely required.

**Comment by bradleyhd** [comment]
Figured as much :) updated both PRs

**Comment by fredemmott** [comment]
Closing in favor of #23

**Pull request closed without merging**
