### PR TITLE
Migrate away from d and v array

### PR DESCRIPTION
**Pull request by lexidor**

### CODE REVIEW

**Comment by lexidor** [comment]
MacOS failure is because of a failed hhvm install:
```
Error: hhvm-4.159: SHA256 mismatch
  Expected: f2a61316967b82b0ac2dc5f4c7fa995cc82d0f5ea3397c09ef8f965450612c75
    Actual: 26379e68f39d059dcce7d58cb97c3f251de0dc17d4e6f0b7ca1618502ddcbee5
```

**Comment by Atry** [comment]
We should revert https://github.com/hhvm/homebrew-hhvm/pull/152

**Comment by lexidor** [comment]
CI run

**Review by Atry — APPROVED** [review]
Looks good to me

**Comment by lexidor** [comment]
CI run

**Review by Atry — APPROVED** [review]
The tests are sophisticated! 👍

**Pull request merged**
